#!/bin/bash
#SBATCH --job-name=align-pool
#SBATCH -A fnrpredator
#SBATCH -t 1-00:00:00 
#SBATCH -N 1 
#SBATCH -n 64
#SBATCH -e %x_%j.err
#SBATCH -o %x_%j.out
#SBATCH --mem=120G

module load bioinfo
module load popoolation2/1201
module load fftw/3.3.8
module load R/4.1.2

#########################################################################
# this script maps read files to the QC reference assembly		#									#
#########################################################################

REF=/scratch/bell/blackan/PUPFISH/C.tularosa/assembly/ncbi/Cyprinodon-tularosa/GCF_016077235.1_ref/GCF_016077235.1.fna
DICT=/scratch/bell/blackan/PUPFISH/C.tularosa/assembly/ncbi/Cyprinodon-tularosa/GCF_016077235.1_ref/GCF_016077235.1.dict
OK=/scratch/bell/blackan/PUPFISH/C.tularosa/assembly/ncbi/Cyprinodon-tularosa/ok.bed



#./PPalign.sh align_wsp.config
 ./PPanalyze.sh analyze_wsp.config 
